name: shunya_vachanasiri
description: "Collection of 12th century Sharana Vachanas in digital format by Shunya Organisation"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.0.0
  firebase_storage: ^12.3.7
  just_audio: ^0.10.4
  just_audio_background: ^0.0.1-beta.11
  audio_service: ^0.18.12
  algolia: ^1.1.2
  speech_to_text: ^7.1.0
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  google_ml_kit: ^0.20.0
  google_mlkit_selfie_segmentation: ^0.10.0  
  cached_network_image: ^3.3.0
  provider: ^6.0.5
  firebase_crashlytics: ^4.3.6
  audioplayers: ^6.5.0
  audio_session: ^0.2.2
  marquee: ^2.2.1
  encrypt: ^5.0.1 
  permission_handler: ^12.0.0+1
  sqflite: ^2.4.1
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  ios: true
  image_path: "assets/icons/ios/svs-logo-3.png"

flutter:
  uses-material-design: true
  assets:
    - assets/splash-anubhava-mantapa.png
    - assets/svs-anubhava-mantapa.png
    - assets/ShunyaBasavanna.png
    - assets/ShunyaSunset.webp
    - assets/om-color.png
    - assets/lotus-om-bw.png
    - assets/icons/ios/svs-logo-3.png
    - assets/svs-lyrics-bg2.jpg

fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
  - fonts:
    - family: NotoSansKannada
      fonts:
        - asset: assets/fonts/NotoSansKannada-Regular.ttf

version: 1.0.0+1
